### ISSUE TITLE
[Compatibility Bug] Precise Mining Breaks scrolling feature from Mouse Tweaks

### ISSUE THREAD

**Issue by JuicyCosmos** [PORTB/precise-mining-minecraft#2]
Game Version 1.16.4, forge version 35.1.36
So after an intense testing I found out that Precise Mining breaks the mouse scrolling feature from Mouse Tweaks. Basically the scrolling feature was supposed to transfer items between inventories when scrolling up/down but this mod bugs it out, causing the tranferred items and the untransferred items to be selected together, essentially breaking the feature.
Even though I don't think there's another mod at play, but
I managed to narrow down the bug-causing list of mods to this for your reference:
![image](https://user-images.githubusercontent.com/79921098/111064643-1ee0d280-84f0-11eb-8a47-7913051c4553.png)

I hope there can be an esay fix, both of these two mods can be a life saver at times!
-Regards

**Comment by PORTB** [comment]
I was not able to replicate the issue with those mods installed (even using those specific versions). I am not sure where your issue is coming from. Are you playing in a modpack?

**Comment by JuicyCosmos** [comment]
I was playing in a modpack made by myself. I don't really know how to make datapacks so the only things I changed were configs. It's really strange that I kept having those issues. But seeing your reply today I decided to try again since last week I went through an arduous process of updating the modpack to 1.16.5. I just tried and the issue is no longer present. Should I close this issue since it's not relevant to me anymore?

**Comment by JuicyCosmos** [comment]
Strange. After closing my creative debug world and load into my survival mod the bug appears again. Changing to creative doesn't help.

**Comment by PORTB** [comment]
Closed, as I cannot reproduce the issue

**Comment by tlitookilakin** [comment]
I was having this same issue in 1.16.5.
