### ISSUE TITLE
[1.12] Precise Mining not working with Tinker's Tools and Mekanism's Atomic Disassembler

### ISSUE THREAD

**Issue by Krutoy242** [PORTB/precise-mining-minecraft#3]
![Tools](https://i.imgur.com/d8p5tMt.png)

When pressing hotkey, *vanilla-like* tools working fine
When i hold **Tinker's Tools** or Mekanism's **Atomic Disassembler**, nothing happens. Tool wont get right NBT tag and control mechanics wont apply.

**Comment by PORTB** [comment]
Fixed in 1.6

**Comment by Krutoy242** [comment]
Thx!
