### ISSUE TITLE
[1.12] Server crash: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft

### ISSUE THREAD

**Issue by Krutoy242** [PORTB/precise-mining-minecraft#4]
MC client run with this mod fine, but when i run server, i got crash with error:
```java
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at thatguy.mod.miningspeed2.MiningSpeed.<clinit>(MiningSpeed.java:28)
	at java.lang.Class.forName0(Native Method)
[...]
```

[crash-2021-04-28_13.05.54-server.txt](https://github.com/PORTB/precise-mining-minecraft/files/6391020/crash-2021-04-28_13.05.54-server.txt)

**Comment by PORTB** [comment]
Should be fixed in 1.7
